export const FIREBASE_PUBLIC_API_KEY =
  process.env.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY;
export const FIREBASE_AUTH_DOMAIN =
  process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN;
export const FIREBASE_PROJECT_ID = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
